language: groovy

cache:
  directories:
    - $HOME/.gradle/caches/

env:
  global:
    - secure: "rSCGQaciH762l0BOwO2gMAo/Q83K6XOENZxgU7k95f4hVeV0JirkWROddp6pUqC3uxA1GxtkBCvMDdVpYzxgnYsJ6KIGvUwwUY4OqWw/CsaYWRCF9rkEkaiH3qSMvyTV5fN5QR5eL7XChSE/ZQ2AHfvpqROEXPWf/cZlGNfJNB4GqPYsr20x5FpuTF3edZW9if//9NmMDMJj8i9SKffslPqmdg4vIe3iF89EThUDvmgOkQh+bLyn6OGfrHqPZfJaA05LaSoa6g8bQXKIvO1MkujgQ4u++8upVaFf1RWhOZyBIocYt7zS61nrfvrceVG1Fw+3X0MjKneRcaAMqsnLsP73ul42N+OqmnpLOdcTBXSog2LTlE9a5oFnoScjSLdGKZ+XWjaS8nR7TI67PrqxHGdAuYFE+rL7cIzbeBCJIsz2MvRj+fmEEBvyx/RT5bgzDALmzCmwvE2KTuFVpp4gTbakyMau1bB0wqAusedT7GlGUb5YiInKbWNKyaOy2XqFqDONVEv28sLR5RbIkX/I+h6K+g0/VczQChchm+WWK081+pk3xJAUQ/TdRIdHC1+wcJWCkLMfUF4zWFjy/PeeZg/IByjjSmCDgUnx0MV8P0AC5bp00LCSkxpOIUIyly/5KMQIxKXh9qe6n8XM5aNTPm9tpswpv5wOPbWSgtWi4r8="
    - secure: "il06G5cX9ToiTdnByomujcSNgJp6+d4JkEiBoHPQj/+pn3LsI+c4kpKzvEB9zf6sSbfXHWCeMC7N1MxGRr5vG/BVySh5JhryuB4rsb1p/zKvaVasZ1+sYckPlfzsn6q0TnLtNoAaPXDRcVFcZPOQPogWXwOZ6diNNEPbL3onbbm35mnZu0WHKZbygfCl8g69+AIGOGwQ1rh4/sc3kKTwiW94+baUic3vBYzIEBd0Cehcv4O61tRDlshJTOds8r3GbZESXSp+NlTLrXdia7FAnrRVLwcm4ymVhE8wjIB4iuHd3FC7PTM+9jQ2F4A70hhFrIGDMkDP7pAAtMzKf+/yBD3TAu2pc7c8BQmmQNt/7A2wVjpDgS+ttA1vgw/0sPEuZMjZ4Pm/2SNTff3PffU6af5UqRkTVFxaGoZk80JfnBaTclX3H3DabAdV7U/vrutGfS5+Pmw5AdriGecz3inkieCDCkyZNHwIAQWdV/y0l7oszatappa1QoKJDuZFdV8w2F0lpWV7OrdOX+kn6s0vfZU8XTtfBcrM3qVNavecTW5uJotCeyFXF/DLfuH3dV+1IngRo3xhUvp7Tw4y7aLUAUxG1SpgZcpPje6U+xHmxDVWkgE/C+u6Tm/5eZRWiCfY/t96tTFZpHuq2oKgrznKA+21WmaWr5qww/DjrXwy83s="
    - secure: "u2fUNhYP22fX4GGOiipfDBzbMl/gP/16Vo9wOo67guryp/8IU2eGqE8oeot2B2kGj9Be/5S/MHftDCooE2GLJrtECbDfk1JolZLaBeq9sMIb8/vkkrIYYA881iryZbYvuWXHwoIxNe40bnzp2i0GMD3QrSWcGr9SM3nlprOET0Q/U6dIa1BQMdfU5iGT5x/9oBkkCwnU1Ro0KHIA/ZxiSDpBoGFXZ7HCJDk17UZWmAS0o7Fm8sJsmkqPIVSJ8cCParGvLOHRL5yRx6G24Z21UuzA3imrKtfrrCU3/DbynQlb2UFi1Dp4AX7xQFfsJlvEiyTH8f5xveXhY+gKqwutwzMfD4HvGJGpaBM5JjsCnakoL7FhWOYTyiKyPCPdxhkl54pwQqlC1h3yPFw2hZRyzjPxz551SmEhNi9WN2m0sbWzIwGniQsI7nTP8zqHz0+bYT2l4J2gvJdPXhdsIn1q3Nu+yX5eLK0gu40VVmVN4f+1Mc7i5jq+ZqaTD9ewxmt9hBa7OAo3uuYdS6u6DsG6uzxI4u39WjW7tbHJ8wxxAHMS94WreS5KYUJdnd0R9nok+qxAaQtyy2XU8MXaOkGD14N5e0IvO36uJj2aYyY6If/ESrGIQuD66jLYcPj131YTPMrz/oOFFAE0PGAQbttg5624Mlo+sbYZTQj9lCrx3KA="

jdk:
  - openjdk11

# The Github user *tt-ci* is the user who will do the git commits initiated by the Gradle Release Plugin.
before_install:
  - echo -e "machine github.com\n  login $TT_CI_TOKEN" > ~/.netrc

# Travis works on detached head. In order to push commits and tags the Gradle Release Plugin needs to
# know the current branch as otherwise it will fail.
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - git checkout $TRAVIS_BRANCH
  - ./gradlew build

deploy:
  provider: script
  script: ./gradlew release -Prelease.preCommitText='[skip travis]' -Prelease.useAutomaticVersion=true -Pgradle.publish.key='$GRADLE_PUBLISH_KEY' -Pgradle.publish.secret='$GRADLE_PUBLISH_SECRET'

# This service will post failing tests directly in PRs.
notifications:
  webhooks: https://www.travisbuddy.com/
